[phases.setup]
nixPkgs = ['python311', 'gcc']

[phases.install]
cmds = [
    'python -m venv --copies /opt/venv',
    '. /opt/venv/bin/activate',
    'pip install --upgrade pip',
    'pip install --no-cache-dir -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'python scripts/railway_start.py'

[variables]
PIP_NO_CACHE_DIR = '1'
PIP_DISABLE_PIP_VERSION_CHECK = '1'
PYTHONUNBUFFERED = '1'
