"""
Vietnamese food category name → English standard category mapping.
Unmapped categories are logged at runtime in normalize.py.
"""

CATEGORY_MAP: dict[str, str] = {
    # Ingredients / raw foods
    "Ngũ cốc": "Cereals",
    "Ngũ cốc và sản phẩm": "Cereals",
    "Khoai củ": "Tubers",
    "Khoai và củ": "Tubers",
    "Đậu đỗ": "Legumes",
    "Đậu và hạt": "Legumes",
    "Rau": "Vegetables",
    "Rau xanh": "Vegetables",
    "Quả": "Fruits",
    "Trái cây": "Fruits",
    "Thịt": "Meat",
    "Thịt và gia cầm": "Meat",
    "Gia cầm": "Poultry",
    "Cá": "Fish & Seafood",
    "Cá và hải sản": "Fish & Seafood",
    "Hải sản": "Fish & Seafood",
    "Trứng": "Eggs",
    "Sữa": "Dairy",
    "Sữa và sản phẩm": "Dairy",
    "Dầu mỡ": "Oils & Fats",
    "Chất béo": "Oils & Fats",
    "Đường mật": "Sugars",
    "Đường và mật": "Sugars",
    "Gia vị": "Condiments",
    "Gia vị và nước chấm": "Condiments",
    "Đồ uống": "Beverages",
    "Nước uống": "Beverages",
    "Hạt và quả hạch": "Nuts & Seeds",
    "Hạt": "Nuts & Seeds",
    # Prepared dishes
    "Món cơm": "Rice Dishes",
    "Cơm": "Rice Dishes",
    "Món phở": "Noodle Dishes",
    "Món bún": "Noodle Dishes",
    "Mì và bún": "Noodle Dishes",
    "Món canh": "Soups",
    "Canh": "Soups",
    "Súp": "Soups",
    "Món xào": "Stir-fry",
    "Xào": "Stir-fry",
    "Món nướng": "Grilled",
    "Nướng": "Grilled",
    "Món kho": "Braised",
    "Kho": "Braised",
    "Món luộc": "Boiled",
    "Bánh": "Baked Goods",
    "Bánh mì và bánh": "Baked Goods",
    "Đồ ăn nhanh": "Fast Food",
    "Ăn vặt": "Snacks",
    "Thực phẩm chế biến": "Processed Foods",
}
