"""convert_food_item_id_to_uuid

Revision ID: 490f9b3ada53
Revises: 004
Create Date: 2025-09-22 22:14:41.923129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '006'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Convert the existing id column from integer to VARCHAR(36) for UUID storage
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("ALTER TABLE food_item ALTER COLUMN id DROP DEFAULT")
    op.execute(
        """
        ALTER TABLE food_item
        ALTER COLUMN id TYPE VARCHAR(36) USING id::text,
        ALTER COLUMN id SET NOT NULL,
        ALTER COLUMN id SET DEFAULT gen_random_uuid()::text
        """
    )


def downgrade() -> None:
    # Convert UUID back to integer (this is destructive - original IDs are lost)
    op.execute("ALTER TABLE food_item ALTER COLUMN id DROP DEFAULT")
    op.execute(
        """
        ALTER TABLE food_item
        ALTER COLUMN id TYPE INTEGER USING id::integer,
        ALTER COLUMN id SET NOT NULL
        """
    )
    op.execute(
        """
        ALTER TABLE food_item
        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
        """
    )
