name: Deploy to Railway

on:
  workflow_dispatch:  # Manual trigger only - choose your branch
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Railway Deployment
        run: |
          echo "Triggering Railway deployment for ${{ github.ref_name }} branch..."

          # Use Railway webhook to trigger deployment
          curl -X POST ${{ secrets.RAILWAY_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "branch": "${{ github.ref_name }}",
              "environment": "${{ inputs.environment }}"
            }'

          echo "✅ Railway deployment triggered successfully!"

      - name: Deployment Info
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Commit: ${{ github.sha }}"
          echo ""
          echo "Check Railway dashboard for deployment status:"
          echo "https://railway.app/"
